appName: nav-dekoratoren
appPath: /dekoratoren
ingresses:
  - https://appres.nav.no/common-html/v4/navno
  - https://www.nav.no/dekoratoren
outboundHosts:
  - www.nav.no
  - navno-unleash-api.nav.cloud.nais.io
env:
  - name: ENV
    value: prod
  - name: XP_BASE_URL
    value: https://www.nav.no
  - name: APP_BASE_URL
    value: https://www.nav.no
  - name: APP_BASE_PATH
    value: /dekoratoren
  - name: API_XP_SERVICES_URL
    value: https://www.nav.no/_/service
  - name: API_DEKORATOREN_URL
    value: https://www.nav.no/person/nav-dekoratoren-api
  - name: MINSIDE_ARBEIDSGIVER_URL
    value: https://arbeidsgiver.nav.no/min-side-arbeidsgiver/
  - name: MIN_SIDE_URL
    value: https://www.nav.no/minside/
  - name: LOGIN_URL
    value: https://login.nav.no/oauth2/login
  - name: LOGOUT_URL
    value: https://login.nav.no/oauth2/logout
  - name: VARSEL_API_URL
    value: https://www.nav.no/tms-varsel-api
replicas:
  min: 2
  max: 8
resources:
  limits:
    memory: 1024Mi
  requests:
    cpu: 1000m
    memory: 256Mi