export const ledetekster: { [key: string]: string } = {
    'footer-arbeids-og-veldferdsetaten': 'Arbeids- og velferdsetaten',
    'footer-arbeids-og-veldferdsetaten-en': 'Arbeids- og velferdsetaten',
    'footer-arbeids-og-veldferdsetaten-se': 'Arbeids- og velferdsetaten',
    'footer-ga-til-innhold-for': 'Gå til innhold for',
    'footer-ga-til-innhold-for-en': 'Gå til innhold for',
    'footer-ga-til-innhold-for-se': 'Gå til innhold for',
    'footer-languages-overskrift': 'Andre språk',
    'footer-languages-overskrift-en': 'Other languages',
    'footer-languages-overskrift-se': 'Andre språk',
    'footer-kontakt-overskrift': 'Kontakt',
    'footer-kontakt-overskrift-en': 'Contact',
    'footer-kontakt-overskrift-se': 'Kontakt',
    'footer-navsamfunn-overskrift': 'NAV og samfunn',
    'footer-navsamfunn-overskrift-en': 'NAV og samfunn',
    'footer-navsamfunn-overskrift-se': 'NAV og samfunn',
    'footer-del-skjerm': 'Del skjerm med veileder',
    'footer-del-skjerm-en': 'Share screen with your tutor',
    'footer-del-skjerm-se': 'Del skjerm med veileder',
    'footer-stikkord-privatperson':
        'Utbetalingsoversikt, saksoversikt, sykefravær',
    'footer-stikkord-privatperson-en':
        'Utbetalingsoversikt, saksoversikt, sykefravær',
    'footer-stikkord-privatperson-se':
        'Utbetalingsoversikt, saksoversikt, sykefravær',
    'footer-stikkord-arbeidsgiver':
        'Tjenester og skjemaer, rekruttering. oppfølging, inkluderende arbeidsliv, hjelpemidler',
    'footer-stikkord-arbeidsgiver-en':
        'Tjenester og skjemaer, rekruttering. oppfølging, inkluderende arbeidsliv, hjelpemidler',
    'footer-stikkord-arbeidsgiver-se':
        'Tjenester og skjemaer, rekruttering. oppfølging, inkluderende arbeidsliv, hjelpemidler',
    'footer-stikkord-samarbeidspartner':
        'Kommuner, utdanningsområdet, psykisk helse, hjelpemidler, leger og behandlere',
    'footer-stikkord-samarbeidspartner-en':
        'Kommuner, utdanningsområdet, psykisk helse, hjelpemidler, leger og behandlere',
    'footer-stikkord-samarbeidspartner-se':
        'Kommuner, utdanningsområdet, psykisk helse, hjelpemidler, leger og behandlere',
    'ga-til-min-side': 'Gå til Min side',
    'ga-til-min-side-en': 'Gå til Min side',
    'ga-til-min-side-se': 'Gå til Min side',
    'logg-inn-knapp': 'Logg inn',
    'logg-inn-knapp-en': 'Log in',
    'logg-inn-knapp-se': 'Sisačáliheapmi',
    'logg-ut-knapp': 'Logg ut',
    'logg-ut-knapp-en': 'Log out',
    'logg-ut-knapp-se': 'Olggosčáliheapmi',
    'logo-title': 'Hjem',
    'logo-title-en': 'Hjem',
    'logo-title-se': 'Hjem',
    'meny-knapp': 'Meny',
    'meny-knapp-en': 'Menu',
    'meny-knapp-se': 'Fállu',
    'meny-knapp-aria-label': 'Menyknapp',
    'meny-knapp-aria-label-en': 'Menu button',
    'meny-knapp-aria-label-se': 'Menyknapp',
    'meny-slideout-ingress': 'I hvilken situasjon er du i?',
    'meny-slideout-ingress-en': 'Choose your current situation',
    'meny-slideout-ingress-se': 'Válljet dilálašvuohta',
    'min-side': 'Min side',
    'min-side-en': 'Min side',
    'min-side-se': 'Min side',
    'pa-min-side-finner-du': 'På Min side finner du:',
    'pa-min-side-finner-du-en': 'På Min side finner du:',
    'pa-min-side-finner-du-se': 'På Min side finner du:',
    'samisk-samegiella': 'SÁMEGIELLA',
    'samisk-samegiella-en': 'SÁMEGIELLA',
    'samisk-samegiella-se': 'SÁMEGIELLA',
    'skiplinks-ga-til-hovedmeny': 'Gå til hovedmeny',
    'skiplinks-ga-til-hovedmeny-en': 'Main menu',
    'skiplinks-ga-til-hovedmeny-se': 'Gå til hovedmeny',
    'skiplinks-ga-til-sok': 'Gå til søk',
    'skiplinks-ga-til-sok-en': 'Search',
    'skiplinks-ga-til-sok-se': 'Gå til søk',
    'skiplinks-ga-til-hovedinnhold': 'Gå til hovedinnhold',
    'skiplinks-ga-til-hovedinnhold-en': 'Main content',
    'skiplinks-ga-til-hovedinnhold-se': 'Gå til hovedinnhold',
    'sok-mobil-knapp': 'Søk',
    'sok-mobil-knapp-en': 'Search',
    'sok-mobil-knapp-se': 'Oza',
    'sok-knapp': 'Søk',
    'sok-knapp-en': 'Search',
    'sok-knapp-se': 'Oza',
    'sok-input-placeholder': 'Søk på nav.no',
    'sok-input-placeholder-en': 'Search on nav.no',
    'sok-input-placeholder-se': 'Oza nav.no',
    'sok-input-label': 'Søk',
    'sok-input-label-en': 'Search',
    'sok-input-label-se': 'Ohcat',
    'tilbake-til-overskrift': 'Tilbake til oversikt',
    'tilbake-til-overskrift-en': 'Back to menu',
    'tilbake-til-overskrift-se': 'Meny vises ikke pa samisk',
    // Todo: Oversett til samisk
    'delskjerm-modal-overskrift': 'Del skjermen din',
    'delskjerm-modal-overskrift-en': 'Share your screen',
    'delskjerm-modal-overskrift-se': 'Del skjermen din',
    'delskjerm-modal-beskrivelse': `Gi veilederen tilgang til å se samme skjermbilde som deg`,
    'delskjerm-modal-beskrivelse-en': `Give the tutor access to see the same screen as you`,
    'delskjerm-modal-beskrivelse-se': `Gi veilederen tilgang til å se samme skjermbilde som deg`,
    'delskjerm-modal-feilmelding': `Må bestå av 5 siffer`,
    'delskjerm-modal-feilmelding-en': `Must be 5 digits`,
    'delskjerm-modal-feilmelding-se': `Må bestå av 5 siffer`,
    'delskjerm-modal-label': `Skriv inn koden du får fra veilederen`,
    'delskjerm-modal-label-en': `Enter the code you received from the tutor`,
    'delskjerm-modal-label-se': `Skriv inn koden du får fra veilederen`,
    'delskjerm-modal-start': `Start skjermdeling`,
    'delskjerm-modal-start-en': `Start screen sharing`,
    'delskjerm-modal-start-se': `Start skjermdeling`,
    'delskjerm-modal-avbryt': `Avbryt`,
    'delskjerm-modal-avbryt-en': `Cancel`,
    'delskjerm-modal-avbryt-se': `Avbryt`,
    'delskjerm-modal-stengt': 'Chatten er stengt',
    'delskjerm-modal-stengt-en': 'Screen sharing is closed',
    'delskjerm-modal-stengt-se': 'Chatten er stengt',
    'varsler-visalle': 'Vis alle dine varsler',
    'varsler-visalle-en': 'Show all your notifications',
    'varsler-visalle-se': 'Vis alle dine varsler',
    'varsler-nye': 'nye',
    'varsler-nye-en': 'new',
    'varsler-nye-se': 'nye',
    varsler: 'Varsler',
    'varsler-en': 'Varsler',
    'varsler-se': 'Varsler',
    'til-forside': 'Til forsiden',
    'til-forside-en': 'Til forsiden',
    'til-forside-se': 'Til forsiden',
    'rolle-privatperson': 'Privatperson',
    'rolle-privatperson-en': 'Privatperson',
    'rolle-privatperson-se': 'Privatperson',
    'rolle-arbeidsgiver': 'Arbeidsgiver',
    'rolle-arbeidsgiver-en': 'Arbeidsgiver',
    'rolle-arbeidsgiver-se': 'Arbeidsgiver',
    'rolle-samarbeidspartner': 'Samarbeidspartner',
    'rolle-samarbeidspartner-en': 'Samarbeidspartner',
    'rolle-samarbeidspartner-se': 'Samarbeidspartner',
    'person-minside-lenke': 'Ditt NAV',
    'person-minside-lenke-en': 'Ditt NAV',
    'person-minside-lenke-se': 'Ditt NAV',
    'arbeidsgiver-minside-lenke': 'Min side - arbeidsgiver',
    'arbeidsgiver-minside-lenke-en': 'Min side - arbeidsgiver',
    'arbeidsgiver-minside-lenke-se': 'Min side - arbeidsgiver',
    'samarbeidspartner-side-lenke': 'Samarbeidspartner',
    'samarbeidspartner-side-lenke-en': 'Samarbeidspartner',
    'samarbeidspartner-side-lenke-se': 'Samarbeidspartner',
    'meny-bunnlenke-minside-stikkord':
        'Utbetalingsoversikt|Saksoversikt|Sykefravær',
    'meny-bunnlenke-minside-stikkord-en':
        'Utbetalingsoversikt|Saksoversikt|Sykefravær',
    'meny-bunnlenke-minside-stikkord-se':
        'Utbetalingsoversikt|Saksoversikt|Sykefravær',
    'meny-bunnlenke-arbeidsgiver-stikkord':
        'Tjenester og skjemaer|Rekruttering|Oppfølging|Inkluderende arbeidsliv|Hjelpemidler',
    'meny-bunnlenke-arbeidsgiver-stikkord-en':
        'Tjenester og skjemaer|Rekruttering|Oppfølging|Inkluderende arbeidsliv|Hjelpemidler',
    'meny-bunnlenke-arbeidsgiver-stikkord-se':
        'Tjenester og skjemaer|Rekruttering|Oppfølging|Inkluderende arbeidsliv|Hjelpemidler',
    'meny-bunnlenke-samarbeidspartner-stikkord':
        'Kommuner|Utdanningsområdet|Psykisk helse|Hjelpemidler|Leger og behandlere',
    'meny-bunnlenke-samarbeidspartner-stikkord-en':
        'Kommuner|Utdanningsområdet|Psykisk helse|Hjelpemidler|Leger og behandlere',
    'meny-bunnlenke-samarbeidspartner-stikkord-se':
        'Kommuner|Utdanningsområdet|Psykisk helse|Hjelpemidler|Leger og behandlere',
    'meny-loading': 'Laster meny-innhold...',
    'meny-loading-en': 'Laster meny-innhold...',
    'meny-loading-se': 'Laster meny-innhold...',
};
