export const ledetekster: { [key: string]: string } = {
    'ga-til-min-side': 'Gå til Min side',
    'ga-til-min-side-en': 'Gå til Min side',
    'ga-til-min-side-se': 'Gå til Min side',
    'logg-inn-knapp': 'Logg inn',
    'logg-inn-knapp-en': 'Log in',
    'logg-inn-knapp-se': 'Sisačáliheapmi',
    'logg-ut-knapp': 'Logg ut',
    'logg-ut-knapp-en': 'Log out',
    'logg-ut-knapp-se': 'Olggosčáliheapmi',
    'logo-title': 'Hjem',
    'logo-title-en': 'Hjem',
    'logo-title-se': 'Hjem',
    'meny-knapp': 'Meny',
    'meny-knapp-en': 'Menu',
    'meny-knapp-se': 'Fállu',
    'meny-knapp-aria-label': 'Menyknapp',
    'meny-knapp-aria-label-en': 'Menu button',
    'meny-knapp-aria-label-se': 'Menyknapp',
    'meny-slideout-ingress': 'I hvilken situasjon er du i?',
    'meny-slideout-ingress-en': 'Choose your current situation',
    'meny-slideout-ingress-se': 'Válljet dilálašvuohta',
    'min-side': 'Min side',
    'min-side-en': 'Min side',
    'min-side-se': 'Min side',
    'pa-min-side-finner-du': 'På Min side finner du:',
    'pa-min-side-finner-du-en': 'På Min side finner du:',
    'pa-min-side-finner-du-se': 'På Min side finner du:',
    'samisk-samegiella': 'SÁMEGIELLA',
    'samisk-samegiella-en': 'SÁMEGIELLA',
    'samisk-samegiella-se': 'SÁMEGIELLA',
    'sok-mobil-knapp': 'Søk',
    'sok-mobil-knapp-en': 'Search',
    'sok-mobil-knapp-se': 'Oza',
    'sok-knapp': 'SØK',
    'sok-knapp-en': 'SEARCH',
    'sok-knapp-se': 'OZA',
    'sok-input-placeholder': 'Søk på nav.no',
    'sok-input-placeholder-en': 'Search on nav.no',
    'sok-input-placeholder-se': 'Oza nav.no',
    'sok-input-label': 'Søk',
    'sok-input-label-en': 'Search',
    'sok-input-label-se': 'Ohcat',
    'tilbake-til-overskrift': 'Tilbake til oversikt',
    'tilbake-til-overskrift-en': 'Back to menu',
    'tilbake-til-overskrift-se': 'Meny vises ikke pa samisk',
    'delskjerm-modal-overskrift': 'Del skjermen din',
    'delskjerm-modal-beskrivelse': `Gi veilederen tilgang til å se samme skjermbilde som deg`,
    'delskjerm-modal-feilmelding': `Må bestå av 5 siffer`,
    'delskjerm-modal-label': `Skriv inn koden du får fra veilederen`,
    'delskjerm-modal-start': `Start skjermdeling`,
    'delskjerm-modal-avbryt': `Avbryt`,
};
