---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: nav-dekoratoren
    namespace: {{namespace}}
    labels:
        team: personbruker
spec:
    image: {{image}}:{{version}}
    port: 8088
    vault:
        enabled: true
    liveness:
        path: /dekoratoren/isAlive
        initialDelay: 10
    readiness:
        path: /dekoratoren/isReady
        initialDelay: 10
    prometheus:
        enabled: true
        path: /dekoratoren/metrics
    replicas:
        min: 2
        max: 4
    ingresses:
        - https://dekoratoren-q1.nais.oera-q.local
        - https://appres-q1.nav.no/common-html/v4/navno
        - https://www-q1.nav.no/dekoratoren
    env:
        - name: XP_BASE_URL
          value: https://www-q1.nav.no
        - name: APP_BASE_URL
          value: https://www-q1.nav.no/dekoratoren
        - name: API_XP_MENY_URL
          value: https://www-q1.nav.no/_/service/no.nav.navno/menu
        - name: API_XP_SOK_URL
          value: https://www-q1.nav.no/_/service/navno.nav.no.search/search2/sok
        - name: API_VARSELINNBOKS_URL
          value: https://www-q1.nav.no/person/varselinnboks
        - name: API_INNLOGGINGSLINJE_URL
          value: https://www-q1.nav.no/innloggingslinje-api/auth
        - name: MINSIDE_ARBEIDSGIVER_URL
          value: https://arbeidsgiver-q1.nav.no/min-side-arbeidsgiver/
        - name: DITT_NAV_URL
          value: https://www-q1.nav.no/person/dittnav/
        - name: LOGIN_URL
          value: https://loginservice-q.nav.no
        - name: LOGOUT_URL
          value: https://loginservice-q.nav.no/slo
        - name: NODE_EXTRA_CA_CERTS
          value: "/etc/ssl/ca-bundle.pem"
    resources:
        limits:
            cpu: '3'
            memory: 1500Mi
        requests:
            memory: 1500Mi
