name: Deploy to Team minside beta
on:
  workflow_dispatch:
    inputs:
      build_mode:
        type: choice
        required: true
        description: 'Build-time NODE_ENV'
        default: 'prod'
        options:
          - prod
          - dev

jobs:
  deploy:
    permissions:
      packages: write
      id-token: write
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      NAIS_VARS: .nais/vars/dev-beta-tms.yaml
      IMAGE_NAME: beta-tms
      CLUSTER: dev-gcp
      BUILD_MODE: ${{ inputs.build_mode }}
    secrets: inherit
